// utils/emailTemplates.js

// 🟢 BASE TEMPLATE (Header & Footer common for all emails)
const baseEmailTemplate = (title, content, headerColor = "#1e3a8a") => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        @media screen and (max-width: 600px) {
          .email-container { width: 100% !important; border-radius: 0 !important; }
          .content-padding { padding: 20px !important; }
        }
      </style>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f7fa; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
      <table width="100%" border="0" cellpadding="0" cellspacing="0" style="background-color: #f4f7fa; padding: 30px 0;">
        <tr>
          <td align="center">
            <table class="email-container" width="600" border="0" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 5px 20px rgba(0,0,0,0.05);">
              
              <!-- HEADER -->
              <tr>
                <td style="background-color: ${headerColor}; padding: 35px 20px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 28px; font-weight: 700; letter-spacing: 1px; text-transform: uppercase;">MPA Research</h1>
                  <p style="color: #e2e8f0; margin: 8px 0 0 0; font-size: 15px; font-weight: 500;">Journal Management System</p>
                </td>
              </tr>

              <!-- BODY CONTENT -->
              <tr>
                <td class="content-padding" style="padding: 40px; color: #374151;">
                  ${content}
                  
                  <div style="margin-top: 40px; border-top: 2px dashed #e5e7eb; padding-top: 25px;">
                    <p style="color: #1f2937; font-size: 16px; font-weight: 600; margin: 0;">Best Regards,</p>
                    <p style="color: #6b7280; font-size: 15px; margin: 5px 0 0 0;">The Editorial Team<br/><b>MPA Research Journal</b></p>
                  </div>
                </td>
              </tr>

              <!-- FOOTER -->
              <tr>
                <td style="background-color: #f8fafc; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb;">
                  <p style="color: #9ca3af; font-size: 12px; line-height: 1.6; margin: 0;">
                    This is an automated notification generated by the <b>MPA Research System</b>.<br/>
                    Please do not reply directly to this email. For any queries, contact admin.
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
};


// 🔴 1. Rejection Email Template (light red, professional)
export const buildRejectionEmail = (researcherName, manuscriptId, feedback, hasAttachment = false) => {
  const content = `
    <h2 style="color: #b91c1c; font-size: 21px; margin-top: 0; font-weight: 600;">Manuscript Status Update</h2>

    <p style="font-size: 16px; line-height: 1.7;">Dear <b>${researcherName}</b>,</p>

    <p style="font-size: 16px; line-height: 1.7;">
      Thank you for submitting your manuscript${manuscriptId ? ` entitled <b>${manuscriptId}</b>` : ""} to <b>MPA Research</b>.
    </p>

    <div style="background-color: #fef5f5; border-left: 4px solid #fca5a5; padding: 18px 20px; margin: 25px 0; border-radius: 6px;">
      <p style="color: #9f1239; margin: 0; font-size: 15px; line-height: 1.8; white-space: pre-wrap;">
        ${feedback || "Following a preliminary administrative and research-integrity compliance assessment, we regret to inform you that your manuscript cannot be considered further and has therefore been rejected at the administrative screening stage."}
      </p>
    </div>

    ${hasAttachment ? `
    <p style="font-size: 14px; color: #6b7280; line-height: 1.6;">
      📎 A detailed evaluation document has been attached to this email for your reference.
    </p>
    ` : ""}

    <p style="font-size: 16px; line-height: 1.7;">
      Please feel free to reach out to us at <a href="mailto:info@mparesearch.com" style="color:#b91c1c; text-decoration:none; font-weight:600;">info@mparesearch.com</a> for any clarifications.
    </p>
  `;
  return baseEmailTemplate("Manuscript Update", content, "#f87171"); // Light Red
};

// 🟠 2. Revision Required Email Template 
export const buildRevisionEmail = (researcherName, manuscriptId, feedback, revisionUrl) => {
  const content = `
    <h2 style="color: #ea580c; font-size: 22px; margin-top: 0;">Action Required: Revisions Requested ⚠️</h2>
    <p style="font-size: 16px; line-height: 1.6;">Dear <b>${researcherName}</b>,</p>
    <p style="font-size: 16px; line-height: 1.6;">The editorial team has reviewed your manuscript <b>${manuscriptId}</b>. Based on the evaluation, revisions are required before it can be processed further.</p>
    
    <div style="background-color: #fff7ed; border-left: 4px solid #ea580c; padding: 15px; margin: 25px 0; border-radius: 4px;">
      <h3 style="color: #9a3412; margin-top: 0; font-size: 16px;">Editorial Comments:</h3>
      <p style="color: #9a3412; margin: 0; font-size: 15px; white-space: pre-wrap;">${feedback || "Please see the attached file for details."}</p>
    </div>
    
    <div style="text-align: center; margin: 35px 0;">
      <a href="${revisionUrl}" style="background-color: #ea580c; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 16px; display: inline-block; box-shadow: 0 4px 6px rgba(234, 88, 12, 0.2);">Upload Revised Manuscript</a>
    </div>
  `;
  return baseEmailTemplate("Revision Required", content, "#ea580c"); // Orange
};

// 🟢 3. Acceptance Email Template
export const buildAcceptanceEmail = (researcherName, manuscriptId, publishDate) => {
  const formattedDate = publishDate
    ? new Date(publishDate).toLocaleString("en-US", {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
    : null;
  const content = `
    <h2 style="color: #16a34a; font-size: 22px; margin-top: 0;"> Manuscript Accepted!</h2>
    <p style="font-size: 16px; line-height: 1.6;">Dear <b>${researcherName}</b>,</p>
    <p style="font-size: 16px; line-height: 1.6;">We are extremely thrilled to inform you that your manuscript <b>${manuscriptId}</b> has successfully passed the peer-review process and is formally <b>Accepted</b> for publication.</p>
    
${formattedDate ? `
  <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; padding: 25px; margin: 25px 0; border-radius: 8px; text-align: center;">
    <p style="margin: 0; font-size: 15px; color: #166534; font-weight: 500;">
      Your manuscript is scheduled to be published on:
    </p>
    <p style="margin: 10px 0 0 0; font-size: 20px; color: #15803d; font-weight: 700;">
      ${formattedDate}
    </p>
  </div>
` : ''}
    <p style="font-size: 16px; line-height: 1.6;">Thank you for your excellent contribution to the academic community through MPA Research.</p>
  `;
  return baseEmailTemplate("Manuscript Accepted", content, "#16a34a"); // Green
};

// 🔵 4. Published Email Template (Used by Cron Job & Direct Publish)
export const buildPublishedEmail = (researcherName, manuscriptId, publishedAt, volume, issue, issueLabel, paperNumber, articleUrl) => {
  const formattedDate = new Date(publishedAt).toLocaleString("en-US", { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const content = `
    <h2 style="color: #4f46e5; font-size: 22px; margin-top: 0;"> Manuscript Published Online!</h2>
    <p style="font-size: 16px; line-height: 1.6;">Dear <b>${researcherName}</b>,</p>
    <p style="font-size: 16px; line-height: 1.6;">Congratulations! Your manuscript has been fully finalized and is now officially <b>Published</b> in the MPA Research journal.</p>
    
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #e0e7ff; border-left: 5px solid #4f46e5; margin: 25px 0; border-radius: 4px;">
      <tr>
        <td style="padding: 20px;">
          <p style="margin: 0 0 10px 0; font-size: 16px; color: #3730a3;"><b>Manuscript ID:</b> <span style="color: #312e81; font-weight: 700;">${manuscriptId}</span></p>
          <p style="margin: 0; font-size: 16px; color: #3730a3;"><b>Date of Publication:</b> ${formattedDate}</p>
          <div style="background-color: #f0f9ff; border-left: 5px solid #0284c7; margin: 25px 0; border-radius: 6px;">
          <div style="padding: 20px;">
            <p style="margin: 5px 0;"><b>Volume:</b> ${volume}</p>
            <p style="margin: 5px 0;"><b>Issue:</b> ${issue} (${issueLabel})</p>
            <p style="margin: 5px 0;"><b>Paper Number:</b> ${paperNumber}</p>
          </div>
        </div>
        </td>
      </tr>
    </table>
    <p style="font-size: 16px; line-height: 1.6;">Your research is now available to the global academic community. Thank you for choosing our platform.</p>
    <div style="text-align: center; margin: 35px 0;">
  <a href="${articleUrl}" 
     style="
       background-color: #4f46e5;
       color: #ffffff;
       padding: 14px 28px;
       text-decoration: none;
       border-radius: 6px;
       font-weight: 600;
       font-size: 16px;
       display: inline-block;
       box-shadow: 0 4px 6px rgba(79, 70, 229, 0.2);
     ">
      View Your Published Paper
  </a>
</div>
  `;
  return baseEmailTemplate("Manuscript Published", content, "#4f46e5"); // Indigo
};

// 🟣 5. Reviewer Invitation Email Template
export const buildReviewerInvitationEmail = (
  reviewerName,
  manuscriptTitle,
  reviewerEmail,
  reviewerPassword
) => {
  const content = `
    <h2 style="color: #2563eb; font-size: 22px; margin-top: 0;">Review Request: MPA Research 📑</h2>
    <p style="font-size: 16px; line-height: 1.6;">Dear <b>Dr. ${reviewerName}</b>,</p>
    <p style="font-size: 16px; line-height: 1.6;">We recognize your expertise in your field and would be honored if you could review a submitted manuscript for our journal.</p>
    
    <div style="background-color: #eff6ff; border: 1px solid #bfdbfe; padding: 20px; margin: 25px 0; border-radius: 6px;">
      <p style="margin: 0; font-size: 13px; color: #1e3a8a; text-transform: uppercase; font-weight: 700; letter-spacing: 1px;">Manuscript Title:</p>
      <p style="margin: 8px 0 0 0; font-size: 16px; color: #1e40af; font-weight: 500;"><i>"${manuscriptTitle}"</i></p>
    </div>
    
    <p style="font-size: 16px; line-height: 1.6;">Please log in to your reviewer dashboard to view the abstract and securely <b>Accept</b> or <b>Decline</b> this invitation.</p>

    <div style="
  background-color: #f8fafc;
  border: 1px solid #cbd5e1;
  padding: 20px;
  margin: 25px 0;
  border-radius: 8px;
">
  <h3 style="
    margin-top:0;
    color:#1e3a8a;
    font-size:16px;
  ">
    Reviewer Login Credentials
  </h3>

  <p style="margin:8px 0; font-size:15px;">
    <strong>Login URL:</strong>
    <a href="https://admin.mparesearch.com">
      https://admin.mparesearch.com
    </a>
  </p>

  <p style="margin:8px 0; font-size:15px;">
    <strong>Email:</strong> ${reviewerEmail}
  </p>

  <p style="margin:8px 0; font-size:15px;">
    <strong>Password:</strong> ${reviewerPassword}
  </p>
</div>

<div style="
  background-color:#fff7ed;
  border-left:4px solid #ea580c;
  padding:18px;
  border-radius:6px;
  margin-top:20px;
">
  <p style="
    margin:0;
    color:#9a3412;
    font-size:14px;
    line-height:1.7;
  ">
    <strong>Note:</strong>
    Please revert back to this mail and cc
    <b>info@mparesearch.com</b>
    for any login-related issues or technical support.
  </p>
</div>
  `;
  return baseEmailTemplate("Review Request", content, "#2563eb"); // Blue
};

// 🟣 6. Reviewer Re-Review (Revised Manuscript) Email Template
export const buildReviewerReReviewEmail = (
  reviewerName,
  manuscriptTitle,
  username,
  portalLink
) => {
  const content = `
    <h2 style="color: #8b5cf6; font-size: 22px; margin-top: 0;">
      Revised Manuscript Ready for Review 🔄
    </h2>

    <p style="font-size: 16px; line-height: 1.6;">
      Dear <b>Dr. ${reviewerName}</b>,
    </p>

    <p style="font-size: 16px; line-height: 1.6;">
      The author has submitted a revised version of the manuscript based on the previous review comments.
      We kindly request you to evaluate the revised manuscript and provide your expert feedback.
    </p>

    <div style="background-color: #f5f3ff; border: 1px solid #ddd6fe; padding: 20px; margin: 25px 0; border-radius: 6px;">
      <p style="margin: 0; font-size: 13px; color: #4c1d95; text-transform: uppercase; font-weight: 700; letter-spacing: 1px;">
        Manuscript Title
      </p>
      <p style="margin: 8px 0 0 0; font-size: 16px; color: #5b21b6; font-weight: 500;">
        <i>"${manuscriptTitle}"</i>
      </p>
    </div>

    <div style="background:#f8fafc; border:1px solid #e2e8f0; padding:20px; border-radius:8px; margin:25px 0;">
      <h3 style="margin-top:0; color:#1e293b;">
        Reviewer Portal Access
      </h3>

      <p style="margin:10px 0;">
        <strong>Portal Link:</strong><br>
        <a href="${portalLink}" target="_blank">${portalLink}</a>
      </p>

      <p style="margin:10px 0;">
        <strong>Username:</strong> ${username}
      </p>

      <p style="margin:10px 0;">
        <strong>Password:</strong> Welcome@123
      </p>
    </div>

    <p style="font-size: 16px; line-height: 1.6;">
      Please log in to the reviewer portal and complete your evaluation at your earliest convenience.
    </p>

    <p style="font-size: 16px; line-height: 1.6;">
      For any assistance regarding access or the review process, kindly reply to this email and keep
      <b>info@mparesearch.com</b> in CC for prompt support.
    </p>

    <p style="font-size: 16px; line-height: 1.6;">
      We sincerely appreciate your valuable contribution to maintaining the quality and integrity of scholarly publishing.
    </p>

    <p style="margin-top:30px;">
      Kind Regards,<br>
      <strong>MPA Research Editorial Office</strong>
    </p>
  `;

  return baseEmailTemplate(
    "Revised Manuscript Review",
    content,
    "#8b5cf6"
  );
};

// 🟢 7. New Submission Email Template (Admin Notification)
export const buildNewSubmissionEmail = (adminName, manuscriptId, manuscriptTitle, authorName) => {
  const content = `
    <h2 style="color: #0f766e; font-size: 22px; margin-top: 0;">New Manuscript Submitted </h2>
    <p style="font-size: 16px; line-height: 1.6;">Dear <b>${adminName}</b>,</p>
    <p style="font-size: 16px; line-height: 1.6;">A new manuscript has just been submitted to the MPA Research Journal and is awaiting your initial editorial review.</p>
    
    <div style="background-color: #f0fdfa; border: 1px solid #ccfbf1; padding: 20px; margin: 25px 0; border-radius: 6px;">
      <h3 style="color: #115e59; margin-top: 0; font-size: 16px; border-bottom: 1px solid #99f6e4; padding-bottom: 10px; text-transform: uppercase; letter-spacing: 0.5px;">Submission Details</h3>
      <table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 15px;">
        <tr>
          <td width="35%" style="padding: 6px 0; font-size: 15px; color: #134e4a; font-weight: 600;">Manuscript ID:</td>
          <td width="65%" style="padding: 6px 0; font-size: 15px; color: #0f766e; font-weight: 700;">${manuscriptId}</td>
        </tr>
        <tr>
          <td width="35%" style="padding: 6px 0; font-size: 15px; color: #134e4a; font-weight: 600;">Submitting Author:</td>
          <td width="65%" style="padding: 6px 0; font-size: 15px; color: #374151;">${authorName}</td>
        </tr>
        <tr>
          <td width="35%" style="padding: 6px 0; font-size: 15px; color: #134e4a; font-weight: 600; vertical-align: top;">Title:</td>
          <td width="65%" style="padding: 6px 0; font-size: 15px; color: #374151; font-style: italic;">"${manuscriptTitle}"</td>
        </tr>
      </table>
    </div>
    
    <p style="font-size: 16px; line-height: 1.6;">Please log in to the Master Admin dashboard to review the files and assign an appropriate editor to this manuscript.</p>
    
    <div style="text-align: center; margin: 35px 0;">
      <a href="${process.env.FRONTEND_URL || '#'}/admin/dashboard" style="background-color: #0f766e; color: #ffffff; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px; display: inline-block; box-shadow: 0 4px 6px rgba(15, 118, 110, 0.2);">Go to Admin Dashboard</a>
    </div>
  `;

  return baseEmailTemplate("New Manuscript Submission", content, "#0f766e"); // Teal
};

// 🟢 9.Editor Assign Email
export const buildEditorAssignmentEmail = (
  editorName,
  manuscriptId,
  manuscriptTitle,
  adminName
) => {
  const content = `
    <h2 style="color: #2563eb; font-size: 22px; margin-top: 0;">
      New Editorial Assignment
    </h2>

    <p style="font-size: 16px; line-height: 1.6;">
      Dear <b>${editorName}</b>,
    </p>

    <p style="font-size: 16px; line-height: 1.6;">
      You have been officially assigned as an <b>Editor</b> by 
      <b>${adminName || "Master Admin"}</b> for the following manuscript.
    </p>

    <!-- Manuscript Box -->
    <div style="background-color: #eff6ff; border: 1px solid #bfdbfe; padding: 20px; margin: 25px 0; border-radius: 8px;">
      
      <h3 style="margin-top: 0; color: #1e40af; font-size: 16px; border-bottom: 1px solid #93c5fd; padding-bottom: 10px;">
        Manuscript Details
      </h3>

      <table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 10px;">
        <tr>
          <td style="padding: 6px 0; font-size: 14px; font-weight: 600; color: #1e3a8a;">
            Manuscript ID:
          </td>
          <td style="padding: 6px 0; font-size: 14px; color: #111827;">
            ${manuscriptId}
          </td>
        </tr>

        <tr>
          <td style="padding: 6px 0; font-size: 14px; font-weight: 600; color: #1e3a8a;">
            Title:
          </td>
          <td style="padding: 6px 0; font-size: 14px; color: #374151; font-style: italic;">
            "${manuscriptTitle}"
          </td>
        </tr>
      </table>
    </div>

    <!-- Instructions -->
    <p style="font-size: 16px; line-height: 1.6;">
      As an editor, you are responsible for:
    </p>

    <ul style="font-size: 15px; line-height: 1.8; color: #374151;">
      <li>Reviewing the manuscript submission</li>
      <li>Assigning appropriate reviewers</li>
      <li>Monitoring the peer-review process</li>
      <li>Providing editorial decisions</li>
    </ul>

    <!-- CTA Button -->
    <div style="text-align: center; margin: 35px 0;">
      <a href="${process.env.FRONTEND_URL}/editor/dashboard"
         style="background-color: #2563eb; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px; display: inline-block; box-shadow: 0 4px 6px rgba(37, 99, 235, 0.2);">
        Go to Editor Dashboard
      </a>
    </div>

    <p style="font-size: 15px; color: #6b7280;">
      Please log in to your dashboard and take necessary action at your earliest convenience.
    </p>
  `;

  return baseEmailTemplate(
    "Editor Assignment",
    content,
    "#2563eb"
  );
};